#!/usr/bin/env bash
# prints string 10 times with a loop
counter=1
while [ $counter -le 20 ]
do
    case $counter in
	4) echo $counter
	   echo bad luck from China
	   ;;
	9) echo $counter
	   echo bad luck from Japan
	   ;;
	17) echo $counter
	    echo bad luck from Italy
	    ;;
    esac
    echo $counter
((counter++))
done
